### ISSUE TITLE
Warning in last version off flutter SDK 3.0.0 "Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null."

### ISSUE THREAD

**Issue by ouais123** [rodrigobastosv/loading_overlay#35] opened 2022-05-14 23:02 UTC

**Comment by rodrigobastosv** [comment] 2022-05-16 14:17
@ouais123 thanks for using this package!

The warning was caused by a dependency. I released a new version of the package with updated versions. Please refer to the version 2.0.7, it has the correction.

Will close the issue for now, but feel free to reopen if needed.

Thanks again

**Closed by rodrigobastosv** 2022-05-16 14:17 UTC
